// Lightweight homepage catalog. Full catalog-data.js is loaded only on data-heavy pages.
globalThis.CS2_CATALOG_PARTIAL = true;
globalThis.CS2_CATALOG = [
  {
    id: "skin-09205674e246",
    name: "AK-47 | 二西莫夫",
    nameEn: "AK-47 | Asiimov",
    nameZh: "AK-47 | 二西莫夫",
    type: "rifle",
    price: null,
    tone: "gold",
    model: "rifle",
    featured: false,
    image: "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu5Dx60noTyLwlcK3wiFO0POlPPNSIeOaB2qf19F6ueZhW2e2wEt-t2jcytf6dymSO1JxA5oiRecLsRa5kIfkYr-241aLgotHz3-rkGoXuUp8oX57",
    source: "CSGO-API / Steam CDN",
    weapon: "AK-47",
    weaponEn: "AK-47",
    weaponZh: "AK-47",
    collection: "头号特训收藏品",
    collectionEn: "The Danger Zone Collection",
    collectionZh: "头号特训收藏品",
    rarity: "隐秘级",
    rarityEn: "Covert",
    rarityZh: "隐秘级",
    quality: "StatTrak / 纪念品",
    qualityEn: "StatTrak / Souvenir",
    qualityZh: "StatTrak / 纪念品",
    wears: ["factory-new", "minimal-wear", "field-tested", "well-worn", "battle-scarred"],
    minFloat: 0.05,
    maxFloat: 0.7,
    paintIndex: "801",
    patternId: "cu_ak47_asiimov"
  },
  {
    id: "sticker-70",
    name: "印花 | Natus Vincere（全息）| 2014年卡托维兹锦标赛",
    nameEn: "Sticker | Natus Vincere (Holo) | Katowice 2014",
    nameZh: "印花 | Natus Vincere（全息）| 2014年卡托维兹锦标赛",
    type: "sticker",
    price: null,
    tone: "ivory",
    model: "sticker",
    featured: false,
    image: "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGJai0ki7VeTHjM-sJnCW8Vli_YTxuAm2FVL_n4DpwipU4_3gav08c6jBWzHElbck5ONvGX2yxU8m6mnXwtetcnOfOgMiCJclRbIMsg74zIPTbZA4cw",
    source: "CSGO-API / Steam CDN",
    weapon: "Team",
    weaponEn: "Team",
    weaponZh: "Team",
    collection: "2014年 EMS 卡托维兹锦标赛挑战组",
    collectionEn: "EMS Katowice 2014 Challengers",
    collectionZh: "2014年 EMS 卡托维兹锦标赛挑战组",
    rarity: "卓越",
    rarityEn: "Remarkable",
    rarityZh: "卓越",
    quality: "Holo",
    qualityEn: "Holo",
    qualityZh: "Holo",
    wears: [],
    minFloat: null,
    maxFloat: null
  },
  {
    id: "skin-4f8d99d09ded",
    name: "AWP | 巨龙传说",
    nameEn: "AWP | Dragon Lore",
    nameZh: "AWP | 巨龙传说",
    type: "rifle",
    price: null,
    tone: "crimson",
    model: "rifle",
    featured: false,
    image: "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu5Dx60noTyLwiYbf_jdk4veqYaF7IfysCnWRxuF4j-B-Xxa_nBovp3Pdwtj9cC_GaAd0DZdwQu9fuhS4kNy0NePntVTbjYpCyyT_3CgY5i9j_a9cBkcCWUKV",
    source: "CSGO-API / Steam CDN",
    weapon: "AWP",
    weaponEn: "AWP",
    weaponZh: "AWP",
    collection: "古堡激战收藏品",
    collectionEn: "The Cobblestone Collection",
    collectionZh: "古堡激战收藏品",
    rarity: "隐秘级",
    rarityEn: "Covert",
    rarityZh: "隐秘级",
    quality: "纪念品",
    qualityEn: "Souvenir",
    qualityZh: "纪念品",
    wears: ["factory-new", "minimal-wear", "field-tested", "well-worn", "battle-scarred"],
    minFloat: 0,
    maxFloat: 0.7,
    paintIndex: "344",
    patternId: "cu_medieval_dragon_awp"
  },
  {
    id: "skin-e728cedb22fe",
    name: "裹手（★） | 警告！",
    nameEn: "★ Hand Wraps | CAUTION!",
    nameZh: "裹手（★） | 警告！",
    type: "glove",
    price: null,
    tone: "ruby",
    model: "glove",
    featured: false,
    image: "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4vx603vRA_Olpfu-TVJ7uK9V6xsLvSEHGaA_uJzsfVhSjuqqh4mpimMlYHGLSLANkI-CcBxQeIMtEHsl4CyNOjm4QDa3dgTniWvjnhJ7Hk54bsEV_Ak-KWE3BaBb-Pt8HWajg",
    source: "CSGO-API / Steam CDN",
    weapon: "裹手",
    weaponEn: "Hand Wraps",
    weaponZh: "裹手",
    collection: "“狂牙大行动”武器箱",
    collectionEn: "Operation Broken Fang Case",
    collectionZh: "“狂牙大行动”武器箱",
    rarity: "非凡",
    rarityEn: "Extraordinary",
    rarityZh: "非凡",
    quality: "普通",
    qualityEn: "Standard",
    qualityZh: "普通",
    wears: ["factory-new", "minimal-wear", "field-tested", "well-worn", "battle-scarred"],
    minFloat: 0.06,
    maxFloat: 0.8,
    paintIndex: "10084",
    patternId: "handwrap_leathery_caution"
  },
  {
    id: "skin-95831ce7c492",
    name: "刺刀（★） | 渐变之色",
    nameEn: "★ Bayonet | Fade",
    nameZh: "刺刀（★） | 渐变之色",
    type: "knife",
    price: null,
    tone: "pearl",
    model: "knife",
    featured: false,
    image: "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu5Dx60noTyLzn4_v8ydP0POvV6JsJPWsAm6Xyfo45-BrHniwzUh24jjVm4qgInnCOA4mDscmEeVcsBXtkN22P-yx5waNg5UFk3tAoG85FQ",
    source: "CSGO-API / Steam CDN",
    weapon: "刺刀",
    weaponEn: "Bayonet",
    weaponZh: "刺刀",
    collection: "反恐精英武器箱",
    collectionEn: "CS:GO Weapon Case",
    collectionZh: "反恐精英武器箱",
    rarity: "隐秘级",
    rarityEn: "Covert",
    rarityZh: "隐秘级",
    quality: "StatTrak",
    qualityEn: "StatTrak",
    qualityZh: "StatTrak",
    wears: ["factory-new", "minimal-wear"],
    minFloat: 0,
    maxFloat: 0.08,
    paintIndex: "38",
    patternId: "aa_fade"
  }
];
