// Lightweight loadout seed. The full catalog is still loaded on demand.
globalThis.CS2_CATALOG_PARTIAL = true;
globalThis.CS2_CATALOG = [
  {
    id: "skin-c14ef2ceee15",
    name: "蝴蝶刀（★） | 渐变大理石",
    nameEn: "★ Butterfly Knife | Marble Fade",
    nameZh: "蝴蝶刀（★） | 渐变大理石",
    type: "knife",
    price: 12325,
    tone: "pearl",
    model: "knife",
    image: "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu5Dx60noTyL6kJ_m-B1Z-ua6bbZrLOmsD2qvzO9ksu1scC-ykRgYvzSCkpu3JCrBPVMkCZIiFLUC40S-l9DkZerg4Qfc3Y9DzCuo3SlK6ydv5e9UA71lpPNwsjHPzA",
    weapon: "蝴蝶刀",
    weaponEn: "Butterfly Knife",
    weaponZh: "蝴蝶刀",
    collectionEn: "Spectrum Case",
    collectionZh: "光谱武器箱",
    rarityEn: "Covert",
    rarityZh: "隐秘级",
    qualityEn: "StatTrak",
    qualityZh: "StatTrak",
    wears: ["factory-new", "minimal-wear"],
    minFloat: 0,
    maxFloat: 0.08
  },
  {
    id: "skin-657a59e6566b",
    name: "爪子刀（★） | 渐变之色",
    nameEn: "★ Karambit | Fade",
    nameZh: "爪子刀（★） | 渐变之色",
    type: "knife",
    price: 12314,
    tone: "ivory",
    model: "knife",
    image: "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu5Dx60noTyL6kJ_m-B1Q7uCvZaZkNM-SD1iWwOpzj-1gSCGn20tztm_UyIn_JHKUbgYlWMcmQ-ZcskSwldS0MOnntAfd3YlMzH35jntXrnE8SOGRGG8",
    weapon: "爪子刀",
    weaponEn: "Karambit",
    weaponZh: "爪子刀",
    collectionEn: "CS:GO Weapon Case",
    collectionZh: "反恐精英武器箱",
    rarityEn: "Covert",
    rarityZh: "隐秘级",
    qualityEn: "StatTrak",
    qualityZh: "StatTrak",
    wears: ["factory-new", "minimal-wear"],
    minFloat: 0,
    maxFloat: 0.08
  },
  {
    id: "skin-b05ee2bf4f0d",
    name: "运动手套（★） | 树篱迷宫",
    nameEn: "★ Sport Gloves | Hedge Maze",
    nameZh: "运动手套（★） | 树篱迷宫",
    type: "glove",
    price: 34759,
    tone: "pearl",
    model: "glove",
    image: "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu5Tk5UvzWCL2kpn2-DFk_OKherB0H_eBC2Ke_uJ_t-l9AX21whwi4Gndnov9JH_FblMlCJYjRbFZtkWww4HnNbjr7wWN39gUmH7gznQeohQBtY8",
    weapon: "运动手套",
    weaponEn: "Sport Gloves",
    weaponZh: "运动手套",
    collectionEn: "Glove Case",
    collectionZh: "手套武器箱",
    rarityEn: "Extraordinary",
    rarityZh: "非凡",
    qualityEn: "Standard",
    qualityZh: "普通",
    wears: ["factory-new", "minimal-wear", "field-tested", "well-worn", "battle-scarred"],
    minFloat: 0.06,
    maxFloat: 0.8
  },
  {
    id: "skin-c1ae7186f829",
    name: "运动手套（★） | 迈阿密风云",
    nameEn: "★ Sport Gloves | Vice",
    nameZh: "运动手套（★） | 迈阿密风云",
    type: "glove",
    price: 12844,
    tone: "ivory",
    model: "glove",
    image: "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu5Tk5UvzWCL2kpn2-DFk_OKherB0H_KfG2Kv0ed4u95lRi67gVNx4T-Bw434IHyVb1QlAsd1FOUDthG4xNznMu3m4QXXg90Wzn_33C1I8G81tLaDi_rK",
    weapon: "运动手套",
    weaponEn: "Sport Gloves",
    weaponZh: "运动手套",
    collectionEn: "Clutch Case",
    collectionZh: "命悬一线武器箱",
    rarityEn: "Extraordinary",
    rarityZh: "非凡",
    qualityEn: "Standard",
    qualityZh: "普通",
    wears: ["factory-new", "minimal-wear", "field-tested", "well-worn", "battle-scarred"],
    minFloat: 0.06,
    maxFloat: 0.8
  },
  {
    id: "skin-2599a8720f89",
    name: "AK-47 | 火蛇",
    nameEn: "AK-47 | Fire Serpent",
    nameZh: "AK-47 | 火蛇",
    type: "rifle",
    price: 10566,
    tone: "ivory",
    model: "rifle",
    image: "https://cdn.cs.trade/images/cs2/wiki/a99b39688873110350a73158380c3958a7840373.avif",
    weapon: "AK-47",
    weaponEn: "AK-47",
    weaponZh: "AK-47",
    collectionEn: "The Bravo Collection",
    collectionZh: "英勇收藏品",
    rarityEn: "Covert",
    rarityZh: "隐秘级",
    qualityEn: "StatTrak / Souvenir",
    qualityZh: "StatTrak / 纪念品",
    wears: ["factory-new", "minimal-wear", "field-tested", "well-worn", "battle-scarred"],
    minFloat: 0.06,
    maxFloat: 0.76
  },
  {
    id: "skin-09205674e246",
    name: "AK-47 | 二西莫夫",
    nameEn: "AK-47 | Asiimov",
    nameZh: "AK-47 | 二西莫夫",
    type: "rifle",
    price: 3150,
    tone: "gold",
    model: "rifle",
    image: "https://cdn.cs.trade/images/cs2/wiki/ec489bf4fae9f6c6185fd9c2c80e16d26acd1af9.avif",
    weapon: "AK-47",
    weaponEn: "AK-47",
    weaponZh: "AK-47",
    collectionEn: "The Danger Zone Collection",
    collectionZh: "头号特训收藏品",
    rarityEn: "Covert",
    rarityZh: "隐秘级",
    qualityEn: "StatTrak / Souvenir",
    qualityZh: "StatTrak / 纪念品",
    wears: ["factory-new", "minimal-wear", "field-tested", "well-worn", "battle-scarred"],
    minFloat: 0.05,
    maxFloat: 0.7
  },
  {
    id: "skin-4f8d99d09ded",
    name: "AWP | 巨龙传说",
    nameEn: "AWP | Dragon Lore",
    nameZh: "AWP | 巨龙传说",
    type: "rifle",
    price: 79800,
    tone: "crimson",
    model: "rifle",
    image: "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu5Dx60noTyLwiYbf_jdk4veqYaF7IfysCnWRxuF4j-B-Xxa_nBovp3Pdwtj9cC_GaAd0DZdwQu9fuhS4kNy0NePntVTbjYpCyyT_3CgY5i9j_a9cBkcCWUKV",
    weapon: "AWP",
    weaponEn: "AWP",
    weaponZh: "AWP",
    collectionEn: "The Cobblestone Collection",
    collectionZh: "古堡激战收藏品",
    rarityEn: "Covert",
    rarityZh: "隐秘级",
    qualityEn: "Souvenir",
    qualityZh: "纪念品",
    wears: ["factory-new", "minimal-wear", "field-tested", "well-worn", "battle-scarred"],
    minFloat: 0,
    maxFloat: 0.7
  },
  {
    id: "skin-bb633c21fc25",
    name: "AWP | 二西莫夫",
    nameEn: "AWP | Asiimov",
    nameZh: "AWP | 二西莫夫",
    type: "rifle",
    price: 1320,
    tone: "teal",
    model: "rifle",
    image: "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu5Dx60noTyLwiYbf_jdk7uW-V6V-Kf2cGFidxOp_pewnF3nhxEt0sGnSzN76dH3GOg9xC8FyEOMOtxa5kdXmNu3htVPZjN1bjXKpkHLRfQU",
    weapon: "AWP",
    weaponEn: "AWP",
    weaponZh: "AWP",
    collectionEn: "The Phoenix Collection",
    collectionZh: "凤凰收藏品",
    rarityEn: "Covert",
    rarityZh: "隐秘级",
    qualityEn: "StatTrak / Souvenir",
    qualityZh: "StatTrak / 纪念品",
    wears: ["field-tested", "well-worn", "battle-scarred"],
    minFloat: 0.18,
    maxFloat: 1
  },
  {
    id: "skin-8e45a15cf7f5",
    name: "M4A1消音版 | 印花集",
    nameEn: "M4A1-S | Printstream",
    nameZh: "M4A1消音版 | 印花集",
    type: "rifle",
    price: 4351,
    tone: "crimson",
    model: "rifle",
    image: "https://cdn.cs.trade/images/cs2/wiki/725a2e029f9467003013a77e171104fc9dd28536.avif",
    weapon: "M4A1消音版",
    weaponEn: "M4A1-S",
    weaponZh: "M4A1消音版",
    collectionEn: "The Operation Broken Fang Collection",
    collectionZh: "“狂牙大行动”收藏品",
    rarityEn: "Covert",
    rarityZh: "隐秘级",
    qualityEn: "StatTrak / Souvenir",
    qualityZh: "StatTrak / 纪念品",
    wears: ["factory-new", "minimal-wear", "field-tested", "well-worn", "battle-scarred"],
    minFloat: 0,
    maxFloat: 0.8
  },
  {
    id: "skin-8c5b9b7ce9f2",
    name: "M4A4 | 皇帝",
    nameEn: "M4A4 | The Emperor",
    nameZh: "M4A4 | 皇帝",
    type: "rifle",
    price: 888,
    tone: "ruby",
    model: "rifle",
    image: "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu5Dx60noTyL8ypexwiVI0P_6afBSJf2DC3Wf09F6ueZhW2exwBh_6m3dnt36InjDPQ4oXJt1TbJeshW_mtfjN-vrsgaKiokWy333kGoXuRj4z9Nd",
    weapon: "M4A4",
    weaponEn: "M4A4",
    weaponZh: "M4A4",
    collectionEn: "The Prisma Collection",
    collectionZh: "棱彩收藏品",
    rarityEn: "Covert",
    rarityZh: "隐秘级",
    qualityEn: "StatTrak / Souvenir",
    qualityZh: "StatTrak / 纪念品",
    wears: ["factory-new", "minimal-wear", "field-tested", "well-worn", "battle-scarred"],
    minFloat: 0,
    maxFloat: 0.8
  },
  {
    id: "skin-cf4c11689014",
    name: "USP消音版 | 枪响人亡",
    nameEn: "USP-S | Kill Confirmed",
    nameZh: "USP消音版 | 枪响人亡",
    type: "pistol",
    price: 540,
    tone: "pearl",
    model: "pistol",
    image: "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu5Dx60noTyLkjYbf7itX6vytbbZSI-WsG3SA_uV_vO1WTCa9kxQ1vjiBpYPwJiPTcFB2Xpp5TO5cskG9lYCxZu_jsVCL3o4Xnij23ClO5ik9tegFA_It8qHJz1aWe-uc160",
    weapon: "USP消音版",
    weaponEn: "USP-S",
    weaponZh: "USP消音版",
    collectionEn: "The Shadow Collection",
    collectionZh: "暗影收藏品",
    rarityEn: "Covert",
    rarityZh: "隐秘级",
    qualityEn: "StatTrak / Souvenir",
    qualityZh: "StatTrak / 纪念品",
    wears: ["factory-new", "minimal-wear", "field-tested", "well-worn", "battle-scarred"],
    minFloat: 0,
    maxFloat: 1
  },
  {
    id: "skin-da5da69785da",
    name: "格洛克18型 | 渐变之色",
    nameEn: "Glock-18 | Fade",
    nameZh: "格洛克18型 | 渐变之色",
    type: "pistol",
    price: 5680,
    tone: "ruby",
    model: "pistol",
    image: "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu5Dx60noTyL2kpnj9h1a7s2oaaBoH_yaCW-Ej-8u5bZvHnq1w0Vz62TUzNj4eCiVblMmXMAkROJeskLpkdXjMrzksVTAy9US8PY25So",
    weapon: "格洛克18型",
    weaponEn: "Glock-18",
    weaponZh: "格洛克18型",
    collectionEn: "The Assault Collection",
    collectionZh: "仓库突击收藏品",
    rarityEn: "Restricted",
    rarityZh: "受限级",
    qualityEn: "Souvenir",
    qualityZh: "纪念品",
    wears: ["factory-new", "minimal-wear"],
    minFloat: 0,
    maxFloat: 0.08
  },
  {
    id: "skin-32a30647e564",
    name: "沙漠之鹰 | 印花集",
    nameEn: "Desert Eagle | Printstream",
    nameZh: "沙漠之鹰 | 印花集",
    type: "pistol",
    price: 690,
    tone: "violet",
    model: "pistol",
    image: "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu5Dx60noTyL1m5fn8Sdk7OeRbKFsJ8-DHG6e1f1iouRoQha_nBovp3OGmdeqInyVP1V0XsYlRbEI50a5wNyzZr605AyI3t5MmCSohylAuC89_a9cBoMY9UkV",
    weapon: "沙漠之鹰",
    weaponEn: "Desert Eagle",
    weaponZh: "沙漠之鹰",
    collectionEn: "The Fracture Collection",
    collectionZh: "裂空武器箱收藏品",
    rarityEn: "Covert",
    rarityZh: "隐秘级",
    qualityEn: "StatTrak / Souvenir",
    qualityZh: "StatTrak / 纪念品",
    wears: ["factory-new", "minimal-wear", "field-tested", "well-worn", "battle-scarred"],
    minFloat: 0,
    maxFloat: 0.8
  },
  {
    id: "skin-91a429af4a60",
    name: "AK-47 | 红线",
    nameEn: "AK-47 | Redline",
    nameZh: "AK-47 | 红线",
    type: "rifle",
    price: 210,
    tone: "pearl",
    model: "rifle",
    image: "https://cdn.cs.trade/images/cs2/wiki/7b5dc50b11995712d0230da035765865f7fa256c.avif",
    weapon: "AK-47",
    weaponEn: "AK-47",
    weaponZh: "AK-47",
    collectionEn: "The Phoenix Collection",
    collectionZh: "凤凰收藏品",
    rarityEn: "Classified",
    rarityZh: "保密级",
    qualityEn: "StatTrak / Souvenir",
    qualityZh: "StatTrak / 纪念品",
    wears: ["minimal-wear", "field-tested", "well-worn", "battle-scarred"],
    minFloat: 0.1,
    maxFloat: 0.7
  }
];
